### ISSUE TITLE
Explore model deployment on onboard computer. 

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#105]

**Comment by jonyktan** [comment]
Referring to which model?

**Comment by okyspace** [comment]
All ML models in general. Was thinking there might be more and more ML models to be deployed on UxVs. 
Could be TartanVO, or some interestingness model, comms?

Was thinking if some model serving engine will help to ease the model deployment (managing versioning, auto-expose APIs, resources). 
Triton Inference Server seems to support edge deployment with C API.  But not sure the performance with UxVs. 
https://github.com/triton-inference-server/server/blob/main/docs/inference_protocols.md#c-api

There will be a meeting with Nvidia and we have asked them to share their experience if any. The meeting is not only focused on this though, I can fwd the link once the meeting is setup if  you are interested.

If not, probably will be just wrapping as ROS nodes, I guessed.
