### ISSUE TITLE
Evaluation of O3DE

### ISSUE THREAD

**Issue by jehontan** [DinoHub/devmgmt-monkeybotics#107]
[Open 3D Engine (O3DE)](https://o3de.org/) is an open source 3D game engine that aims to support the development of AAA-quality games. It is the succesor to Amazon's Lumberyard and is used in Amazon's New World MMORPG.

Being open source, O3DE requires no paid license and is hackable, making it an attractive candidate for building a common simulation environment and related tooling.

O3DE will need to be evaluated for the following (additional requirements welcome):
- [ ] Physics-based rendering support
- [ ] Physics engine functionality (friction, deformables, fluids)
- [ ] Sensor simulation support (lidar, radar, EO/TI)
- [ ] Realtime performane, hardware acceleration support
- [ ] Asset compatibility, asset/plugin ecosystem
- [ ] Scripting support

**Comment by jehontan** [comment]
Suggest to close or deprioritize. Engine is in alpha and not stable for use. Most collaborators are likely to be on Gazebo/Unity/Unreal.

**Comment by jonyktan** [comment]
Am ok. Thanks! Just update at Sprint Review.
