### ISSUE TITLE
Try out LIDAR with a SLAM module. Hardware testing. 

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#113]
DONE if SLAM module can run with Livox Mid-70, localize to less than 2m error (arbitrarily?) in DF, and produce human-readable pointcloud map.

**Comment by Blqe** [comment]
Testing in office on 3 Nov

**Comment by jw5410** [comment]
![image.png](https://images.zenhubusercontent.com/60decf83edddede6324e1e95/f3a9fff6-0840-40ed-ad8e-ce930116b022)![image.png](https://images.zenhubusercontent.com/60decf83edddede6324e1e95/df218c08-d91c-45ad-9349-faeb1c5b802c) livox_mapping tested. Some angular drift when we pivot hence misaligned pointcloud upon looping back to start point. Will try with IMU and loop closure on 12 Nov 2021

**Comment by eehantiming** [comment]
![run1_swsync.png](https://images.zenhubusercontent.com/613aeb85c5a13df9fbc5d621/05069cdc-3804-484e-868a-cc733350dcf0)
Ran FAST-LIO (lidar + IMU) at digifac

**Comment by jonyktan** [comment]
Any branch that you worked on that we should fork to DinoHub? E.g. for the SLAM module that you used.

@eehantiming

**Comment by eehantiming** [comment]
still testing out multiple repos with minimal changes, for now forked FAST-LIO to https://github.com/DinoHub/FAST_LIO

**Comment by eehantiming** [comment]
testing https://github.com/Innopolis-UAV-Team/LIO-SAM/tree/livox instead for LIO-SAM which has support for livox lidar

**Comment by eehantiming** [comment]
> testing https://github.com/Innopolis-UAV-Team/LIO-SAM/tree/livox instead for LIO-SAM which has support for livox lidar

LIO-SAM: cant work with livox yet
Loam-Livox: tested loop closure, require more testing
r2live: runs with rosbag, yet to test with actual camera
FAST-LIO-SLAM (FAST-LIO with scan context for loop closure) - not tested yet
