### ISSUE TITLE
UAV/UGV should be able to detect proxy target(s) in FPV videos.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#119]
FPV drone detection of cars/buses:
https://www.youtube.com/watch?v=0VxDOGcWD2E
FPV city dataset (kuala lumpur)
https://www.youtube.com/watch?v=trzykfEDShc
FPV city test footage** not dataset
FPV through a plywood factory with ppl inside
https://www.youtube.com/watch?v=zP-gTCp5Kac
FPV (people on water at 0:36)
https://www.youtube.com/watch?v=cKW4W7hd1S4
FPV (people walking around indoor building)
https://www.youtube.com/watch?v=yXEb0fWLJIY
FPV (lower res; detection of person at 0:36 in oil palm)
https://www.youtube.com/watch?v=WSEWjYUubs4

- [ ] Understand the limitation of CV model based on cam sensor specifications

**Comment by okyspace** [comment]
Tackle the DF video first. Timelinewise for this task will be Dec21.

**Comment by dbxwong** [comment]
additional footage. @timothymah  can see if OK for yr proj:

https://www.youtube.com/watch?v=RiDHgoYv10w 
(0:16 - 0:43) UAV overhead view of crew served wpn on jeep
(1:03-1:08) truck driving into shelter

**Comment by jinmingteo** [comment]
hihi, i have uploaded some of the inference video here 
https://drive.google.com/drive/folders/1ODl1QMmnfTR0ygS-7sGWV5jrvLTGHspM

however, i am out of personal gdrive storage to upload the remaining ones. Can someone take over the ownership of the videos? 

Thanks!

**Comment by okyspace** [comment]
Pass the video to us, we can upload.
