### ISSUE TITLE
Understand TARE architecture and adapt the structure for future modules.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#16]

**Comment by seeeheng** [comment]
Definition of done:
- Documentation of functions available using Doxygen or similar documentation. Currently 50% done.
- Complete documentation of source code pushed into documentation branch. Merge to main when reviewed.

Required hours: 
- about 40-50 more to finish and tidy up.

**Comment by seeeheng** [comment]
Simplified documentation (detailed documentation on .cpp files)
https://docs.google.com/document/d/1zRdz_ZereKRhIvDKGTDsSLPGwcOteyARl1FB8yge-fo/edit?usp=sharing

**Comment by seeeheng** [comment]
SubT
https://docs.google.com/document/d/17CKdaZfO5VFX2QrNHe_5VOL_etHH_E4FWLfB0bEXst4/edit?usp=sharing

**Comment by seeeheng** [comment]
Merged.
https://github.com/DinoHub/tare_planner/commit/11335e2cd6b58be61029d6d66c8bd65d3d76b5b0
