### ISSUE TITLE
UAV should be able to move between indoors and outdoors. Ingress and egress buildings.Vertical ingress and egress.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#19]
- [x] Video Capture of UAV Ingress building
- [x] Video Capture of UAV Egress building
- [x] Video Capture of UAV Vertical ingress
- [x] Video Capture of UAV Vertical egress

**Comment by Blqe** [comment]
Test if working in simulation

**Comment by okyspace** [comment]
Dylan will do a test to confirm in the simulation.

**Comment by amokduke** [comment]
The UAV after the initial scan, move into the building as part of its auto-explore algo:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/787962df-4728-4476-81c4-432bb5a007c8)

The UAV flew out of the building when a manual waypoint is issued to the UAV when it is exploring the inside:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/d49c87ff-9a8c-4317-9b34-4768389d2596)

The UAV continues to explore the outside of the building until a manual waypoint is issued to go back into the building:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/b945d6b2-ecbd-4ee8-a6f0-4d959c8fda15)
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/7a80e2b4-ac75-4465-a658-7af86f36a0a4)

Full Video Capture:
https://drive.google.com/file/d/1vH0XZlpooachVw-rZawAo-2dZS-u5fYj/view?usp=sharing

**Comment by amokduke** [comment]
The UAV was able to Vertical ingress by giving it manual waypoints:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/ff7c5814-4e94-45fb-adc6-41ed8c411223)
Note: The "g" button in RViz issues waypoints in "2D". Use the CLI to issue waypoint with "height" 3D

Full Video Capture:
https://drive.google.com/file/d/1q64NIyXU3RXQ5xpjcV8X3Ks7VTNFQHv8/view?usp=sharing

**Comment by amokduke** [comment]
The UAV was able to Vertical egress by giving it a manual waypoint:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/9db200c4-6f13-4681-9879-2b6cedfbb2dd)

Full Video Capture:
https://drive.google.com/file/d/1z_xvEgwIQXI9fgqiDWBRCTp7yQ6kfgwP/view?usp=sharing
