### ISSUE TITLE
UAV/UGV should be able to detect proxy target(s) in videos.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#57]
DoD:
1. Target detection model evaluated in videos (emulating envs and targets). Assessment documented. (12 hours)

Proposed to do list: 

- [ ] List down proxy targets and envs type for each project. 
- [ ] List down videos (emulating envs + targets) for evaluating the target detection model. 
- [ ] Source and train up model, where applicable. 
- [ ] Work out metrics. 
- [ ] Evaluate model.

**Comment by okyspace** [comment]
DF video done up. CV can take the videos and run their CV algor, capture recording to review with user.

**Comment by okyspace** [comment]
Capture FPV videos for high speed flying. This is more UAV.

**Comment by okyspace** [comment]
https://www.youtube.com/watch?v=zP-gTCp5Kac 
https://www.youtube.com/watch?v=cKW4W7hd1S4
https://www.youtube.com/watch?v=yXEb0fWLJIY

**Comment by okyspace** [comment]
https://github.com/mlaiacker/rosbag2video

**Comment by Blqe** [comment]
UF completed, DF not done

**Comment by okyspace** [comment]
Shifted the task to detect target in FPV videos to task #119

**Comment by Blqe** [comment]
Jeremy uploaded mp4 version

**Comment by jonyktan** [comment]
Any branch that you worked on that we should fork to DinoHub?

@jinmingteo @ernestlwt

**Comment by dbxwong** [comment]
does anyone have the links that @ernestlwt @jinmingteo  shared about detecting a bunch of us in DF?
