### ISSUE TITLE
Discuss and decide overarching framework

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#86]
**Description**
- To decide how we should build up our modules. 
- ROS, ROS2, ROS-I, ROS-M?
- Subsequent modules development to be based on this framework which will affect how modules communicate with each other. 

**DoD:**
1. Decision points and assessment for framework to be used.
- e.g. market adoption rate, EOL, ease of upgrading, backward compatibility, current state of robustness/quality, etc

**Proposed to do:**
1. Determine if we can use ROS-I or ROS-M from licensing, etc. 
2. If ROS-I and ROS-M is not the way / not going to be clear but they are based on ROS2, start from ROS2 as our framework? Meaning all open source modules to be ported over to ROS2 and integrate?

**Comment by okyspace** [comment]
Consolidated some points and discussion points in slide 40 onwards. https://docs.google.com/presentation/d/1WGM_1nbvuweDumJm5APrbs7A5u6ye1Ea34H0QSTXCxw/edit#slide=id.gf9e6518706_0_58

**Comment by okyspace** [comment]
Shifted discussion points to this slide: https://docs.google.com/presentation/d/1hYBFoW6CE-AmSxVj2OgMQL2mucRKnf7b/edit?usp=sharing&ouid=112437234591437978761&rtpof=true&sd=true
@jonyktan, for your comment.

Will add on ROS, ROS2 comparison but don't think is critical for the discussion.

**Comment by jonyktan** [comment]
Thanks for organising the points!

1. For speed of experimentation, "plug and play" model, follow the ROS version that we get the package from (e.g. RI or open source).
1. Unknown is whether ROS will create problems for us later on when safety/reliability become important.
1. For mode where we write our own modules, we have the luxury to write directly in ROS2. Then need to implement bridge to interface with other modules that may be on ROS. Also depends on whether we want to write our own modules.

So yes, I think ROS/ROS2 technical comparison not so crucial anymore. Mainly is to find out why the more "deployment" types like ROS-I and ROS-M cannot be on ROS.

**Comment by jonyktan** [comment]
Since a later consideration is the ease of software/system testing to ensure compliance with quality/safety standards, I'm compiling a list of standards that are potentially relevant to our systems. 

https://docs.google.com/spreadsheets/d/1a0rNVKEzSV4wAvW4zdmt0tneSXCGyX5AO3E9JkXMVCM/edit?usp=sharing

**Comment by okyspace** [comment]
Website that guides the ROS 2 design effort.
https://design.ros2.org/

**Comment by okyspace** [comment]
Updated slide based on today 18nov2021 discussion. 
https://docs.google.com/presentation/d/1hYBFoW6CE-AmSxVj2OgMQL2mucRKnf7b/edit#slide=id.p12

**Comment by okyspace** [comment]
Discussion outcomes. 

![image.png](https://images.zenhubusercontent.com/61303ce5004bdd1fb7b7cf77/2afda0a9-1507-451c-850b-a421d16963a8)

**Comment by okyspace** [comment]
Discussion done and notes updated in slide. 
For agreement to close this task in coming sprint review.

**Comment by jonyktan** [comment]
The summary looks good!
