### ISSUE TITLE
SV OR Study Scenarios for SubT Stack

### ISSUE THREAD

**Issue by amokduke** [DinoHub/devmgmt-monkeybotics#93]
- [x] Digital Factory Level 1: https://drive.google.com/file/d/1W9ct0CA1gcGAtI1wdX-Dz10OMQJz7R92/view?usp=sharing

- [x] Big Office: https://drive.google.com/file/d/1FsqL8zFd_4xIDR36omP4yWYzMvxDbQ-V/view?usp=sharing 

- [x] Forest: https://drive.google.com/file/d/1B_lcWajLMyUqwTannq31tuDqnwW8ON1u/view?usp=sharing

**Comment by amokduke** [comment]
World files of the scenarios are retrievable from the CMU Bitbucket:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/cf19d04a-7dc2-46e4-9a4f-4f8ff97e3d66)

**Comment by amokduke** [comment]
Shall we fall back to Melvin's forest scenario?

**Comment by amokduke** [comment]
From 20th Oct 2021 sprint review, we will use a smaller model of Ling Ling's forest. @jw5410, you got some tools to crop the model?

**Comment by amokduke** [comment]
Tried to run the updated forest but keep facing an old error: https://app.zenhub.com/workspaces/infrastructure-60ac72f13e47e6000f7a34a2/issues/katcujic-cmu/dsta-zenhub/84

Usually, this alignment issue will go away after restarting but not for me.  Decided to build everything and realised that CMU's accounts given to us has expired. Has updated the qns list for Kevin.

**Comment by amokduke** [comment]
Kevin has reinstated the accounts, but some of the repo that we used to access is still denied:
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/e0292621-1cb9-4d93-93ff-5a952cc678c0)

Have asked Kevin to reinstate access to the repo: 
![image.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/2a566383-cacd-43c9-ae34-f8226febb392)

**Comment by amokduke** [comment]
Debug with Ling Ling. Realised the issue is the terrain at the spawn point. It needs to be at "0" height.

Forest 4 model: https://drive.google.com/file/d/1btWIKcs4EVeMIXgvQ334n2JDdmv8FNEk/view?usp=sharing

Video Capture of the exploration: https://drive.google.com/file/d/1lHkZbh_5UJAc-tD1GH_W6ZbtAbeA1S61/view?usp=sharing

However, at the 6 min+ mark, the simulation hung.

**Comment by amokduke** [comment]
Completed the Forest scenario with "Forest 5" model here: https://drive.google.com/file/d/1aVFjqkFfAG4lpy3zJXpSWWwY8JDyY85C/view?usp=sharing

![Screenshot from 2021-11-29 17-33-48.png](https://images.zenhubusercontent.com/60af601746d84465c9496341/08d8ffc0-1bbd-45ac-af5f-8a0fd8db6908)

Video Capture:
https://drive.google.com/file/d/1B_lcWajLMyUqwTannq31tuDqnwW8ON1u/view?usp=sharing

**Comment by slinglin** [comment]
Forest_5 was optimized by 

1) reducing number of trees by decreasing area for tree planting, and
2) joining trees as similar collection group within blender

The terrain lowest ground height were transformed to be slightly below "0" height.  Maybe something to take note in future when designing terrains if to be run with the simulator.
