### ISSUE TITLE
Exploration of using thin clients to connect to UE environment to do TartanAir base on a single UE4 server. 

### ISSUE THREAD

**Issue by teowzh** [DinoHub/devmgmt-monkeybotics#96]

**Comment by Blqe** [comment]
Final check in AIP

**Comment by AlexanderWCX** [comment]
Tested that pixel streaming works, and was working on shrinking down the docker image size as it is quite big, but on feedback, will be working on getting it running on AIP first

**Comment by AlexanderWCX** [comment]
Current working setup is one thin to one streaming instance

**Comment by teowzh** [comment]
AIP is able to run thin clients and connect the the pixel streaming server
