### ISSUE TITLE
Take stock questions on what we need to ask CMU on the multiUxVs modules and architecture.

### ISSUE THREAD

**Issue by okyspace** [DinoHub/devmgmt-monkeybotics#98]

**Comment by jonyktan** [comment]
https://docs.google.com/spreadsheets/d/1RBA6GgNYEBhcEZPFQ6cWky3QyYcKzEHeH5Yr4jqG2gk/edit?usp=sharing

**Comment by Blqe** [comment]
3 Nov, 8pm

**Comment by okyspace** [comment]
@Blqe Why is this closed? If it is done, it should be under Done.

**Comment by Blqe** [comment]
Shifted to done paiseh

**Comment by okyspace** [comment]
No problem. Actually when I took closer look, maybe you are correct. If we do not shift them to closed, it will remain open in github repo. Not a concern though. Suggest we look into what Zenhub uses Done for, and adjust accordingly.
